### ISSUE TITLE
Update to 0.1.2

### ISSUE THREAD

**Issue by rcmaniac25** [google/google-api-cpp-client#2]
The most recent generated service APIs specify their language_version is 0.1.2 where as the drive and calendar builds that come with this repo specify 0.1. Which makes sense giving that this is API 0.1.

In short, update to 0.1.2

**Comment by snnn** [comment]
Hi @rcmaniac25 , I created a pull request for it:
https://github.com/google/google-api-cpp-client/pull/12

**Comment by rcmaniac25** [comment]
Thanks @snnn. Was this generated or did you hand-write the code? Because I had written some of the missing functionality for my fork, but I'm debating on merging yours in (as I think this repo is dead otherwise)

**Comment by snnn** [comment]
@rcmaniac25 I only did some minor changes in 5 files :

src/googleapis/client/service/service_request_pager.h
src/googleapis/client/service/test/service_request_pager_test.cc
src/googleapis/client/util/date_time.h
src/samples/calendar_sample_main.cc
src/samples/gdriveutil_main.cc

Because Google is doing a migration which replaces all mixed underscore/camelCase names (e.g. set_pageToken), which uniform underscored names (set_page_token). (ref: https://groups.google.com/forum/#!topic/google-api-cpp-client/0R3w9gvGOjY) 

The others (service_apis/calendar &&  service_apis/drive) were downloaded from http://google.github.io/google-api-cpp-client/latest/available_service_apis.html

Please check it for me. Thanks.

**Comment by rcmaniac25** [comment]
Ok, I did something similar but I don't think I changed underscore/camelCase. I'll check it later, as I may merge your fork into mine because of the underscore change.

**Comment by aiuto** [comment]
On Fri, Jan 2, 2015 at 2:32 AM, Changming Sun <notifications@github.com>
wrote:

> @rcmaniac25 <https://github.com/rcmaniac25> I only did some minor changes
> in 5 files :
>
> src/googleapis/client/service/service_request_pager.h
> src/googleapis/client/service/test/service_request_pager_test.cc
> src/googleapis/client/util/date_time.h
> src/samples/calendar_sample_main.cc
> src/samples/gdriveutil_main.cc
>
> Because Google is doing a migration which replaces all mixed
> underscore/camelCase names (e.g. set_pageToken), which uniform underscored
> names (set_page_token). (ref:
> https://groups.google.com/forum/#!topic/google-api-cpp-client/0R3w9gvGOjY)
>
​Yes. Underscores is our C++ style.​ The generated libraries might still be
generating method names in both formats, but that is going to stop soon.

 The others (service_apis/calendar && service_apis/drive) were downloaded
> from
> http://google.github.io/google-api-cpp-client/latest/available_service_apis.html
>
​That is the best place to get current versions of an API. As APIs have
minor revisions, the new code shows up there automatically.
​

**Comment by rcmaniac25** [comment]
Ok, I ended up merging @snnn's changes for the underscore changes. I also saw that he did (smarter then my own) "typedef DateTime Date;" while I had originally implemented a Date class and essentially copied the content from DateTime to it.

**Comment by aiuto** [comment]
Got it. I may do a roll up of little fixes that we have made internally and
push them out. I'll look at the date class along with that.

**Comment by aiuto** [comment]
I merged in the pull request. That was to the v0.1 branch.
master, however, is the new default branch, where I have done a similar update.
