### ISSUE TITLE
admin API doesn't compile once unzipped

### ISSUE THREAD

**Issue by rcmaniac25** [google/google-api-cpp-client#3]
The CMakeList file points to the wrong directory, or the source is in in a extra directory then what it should be.

api: [admin](https://google-api-client-libraries.appspot.com/resources/api-libraries/download/admin/reports_v1/cpp)
version: reports_v1 
rev: 30

**Comment by aiuto** [comment]
The admin suite of APIs use some unusual features of the API Discovery format to group themselves into the same package. My guess is that the template for CMakeLists.txt does not do the right thing w.r.t. that.

The real place to fix this is not in this project, but in the library generator. The actual file which needs changing is probably this one:  https://code.google.com/p/google-apis-client-generator/source/browse/src/googleapis/codegen/templates/cpp/default/templates/___package___/CMakeLists.txt.tmpl

My back of the envelope calculation is that this will take a couple hours to do, some email negotiation, about four hours for me to integrate the change, test and push back to the repo. My guess is that the user base for this API with CMake is small enough not to warrant it. In any case the fix is not in this project it is in the other one.

**Comment by rcmaniac25** [comment]
That's fine. I will admit, I was just filing issues. Not necessarily something that I'm using/going to use "soon".
